name: radio_station
description: Podcast Application



publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  smooth_page_indicator: ^1.0.0+2
  flutter_native_splash: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  adobe_xd:

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - asset_files/
    - asset_files/svg/
    - asset_files/png/
    - asset_files/fonts/Circular-Std-Book.ttf

  fonts:
    - family: Circular
      fonts:
        - asset: asset_files\fonts\Circular-Std-Book.ttf