name: radio_station
description: Radio and Podcast Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  smooth_page_indicator: ^1.0.0+2
  flutter_native_splash: ^2.2.9
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  adobe_xd:

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/png/bottom_navigation_icons/
    - assets/png/cover/
    - assets/png/events/
    - assets/png/icons/
    - assets/png/popular_broadcasts/
    - assets/png/similar_broadcasts/
    - assets/png/tutorial/
    - assets/png/splash_screen/

  fonts:
    - family: Circular
      fonts:
        - asset: assets\fonts\Circular-Std-Book.ttf

    - family: HK_Bold
      fonts:
        - asset: assets\fonts\HKGrotesk-BoldLegacy.otf

    - family: HK_Medium
      fonts:
        - asset: assets\fonts\HKGrotesk-MediumLegacy.otf